name: Multi Website Scanner

on:
  schedule:
    - cron: "*/10 * * * *"   # runs every 10 minutes

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install requests beautifulsoup4

      - name: Run bot
        run: python bot.py
