name: Multi Website Scanner

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Requests
        run: |
          pip install -r requirements.txt

      - name: Run Scanner
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py

      - name: Save Hash File
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          git add website_hashes.json

          git commit -m "Update hashes" || echo "No changes"

          git push
